version: '3.9'
services:
  db:
    container_name: simple_postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes: 
      - "D:/docker/volumes/postgres/scripts/:/my_scripts"
      - "D:/docker/volumes/postgres/data/:/var/lib/postgresql/data"
     
volumes:
  db:
    driver: local
